### PR TITLE
Feature subpages

### PR DESCRIPTION
**Pull request by dervism**
I have extended Minimal with a feature that allows users to add pages to a folder called _sitepages and to automatically get links to those pages just below the header. I added this feature to one of my own projects and wanted to contribute it back to the Minimal-project. I would love to get a review and your thoughts around this. I kept this feature as simple as possible, so no highlighting of selected page or other fancy styling.

*What I have commited:*
I have updated the default layout, added a new layout called "page.html", added 3 sample pages in the `_sitepages` folder and updated the README file with how-to. I have also added the "--assume-extension" flag to html-proofer in cibuild to correctly test the pages. 

This is my first time contributing to a GitHub-theme, so I am not sure whether to keep the 3 samples pages (in the `_sitepages` folder) or to delete them. I kept them for now so you could take a look at it.

*How does it look:*
Below is an image of how these 3 sample pages will look on the generated site.

image

### CODE REVIEW

**Comment by benbalter** [comment]
@dervism thanks for this! Rather than creating a new collection, (what's the difference between a page and a sitepage?), would a `subpage` or similar front-matter or config flag make more sense?

**Comment by dervism** [comment]
@benbalter You are absolutely correct. I have simplified the code now. It uses `site.pages` instead now. All pages (if their `title` property is defined) will be included in the sidebar. A user can now hide a page by setting `sidebar` to false. I have updated the documentation about this. 

With this change, I do not need the demo pages I added (I can test it `another-page.html` that exists in your repo), so I deleted that folder to keep this PR as small as possible. I can add it back if you think it's ok to have them there.

**Comment by ShaneCurcuru** [comment]
Exactly one of the simple yet useful features I've been looking for in this theme! 👍

**Comment by dervism** [comment]
@benbalter I love to have a second review of the changes you requested.

**Comment by dervism** [comment]
I am closing this due to no answer. Please feel free to open it if anyone wishes the same feature.

**Pull request closed without merging**
