### PR TITLE
Update Google Analytics

### LINKED ISSUE #88: Google Analytics
How can I add google analytics to my page? 

Although I added an analytics.html file into the _includes folder and linked it to the config.yml file but google could not pull any data.

my page: https://omerayyildiz.com/nishgt
my repository: https://github.com/omerayyildiz/nishgt

### PR DESCRIPTION
**Pull request by pedrominicz**
Closes #88

### CODE REVIEW

**Review by andresakata — COMMENTED** [review]
According to the documentation, it's recommended to put the gtag.js into the `<head>`.

From the setup procedures:

> Copy the global site tag into the <head> section of your HTML.

**Comment by parkr** [comment]
Hi! You can now customize the Google Analytics code by using an include in your site: https://github.com/pages-themes/cayman#customizing-google-analytics-code

**Comment by ZenaMel** [comment]
@parkr Why is this closed? I just wasted around 20-30 minutes with this not being merged. The PR looks fine.

Can we replace `head-custom-gogle-anlytics.html` -->

```html
{% if site.google_analytics %}
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '{{ site.google_analytics }}', 'auto');
    ga('send', 'pageview');
  </script>
{% endif %}
```

with 

```html
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', '{{ site.google_analytics }}');
    </script>
```

As per Google's official recommendation?

This removes the need for users to manually create the file themselves and being a bit lost as to why GA isn't working.

**Comment by ZenaMel** [comment]
> Hi! You can now customize the Google Analytics code by using an include in your site: https://github.com/pages-themes/minimal#customizing-google-analytics-code

This is cool but having the default be compatible with Google V4 would make more sense IMHO.

**Comment by shyamal-anadkat** [comment]
can we re-open this?

**Pull request closed without merging**
